#!/usr/bin/env php
<?php

require_once __DIR__ . '/vendor/autoload.php';

/**
 * @return bool
 */
function is_win()
{
    return (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN');
}

// Using UTF-8 if the program is running on Windows.
(is_win()) and exec('chcp 65001', $msg);

$file = isset($argv[1]) ? $argv[1] : null;
if (! $file) {
    file_put_contents('php://stderr', 'The basic command usage: php mycsv [file.txt]');
    exit;
}elseif (! file_exists($file)) {
    file_put_contents('php://stderr', "'$file' doesn't exist.");
    exit;
}

$fd = fopen($file, 'r');
$parser = new \MyCsv\ParseWalker();

while (($buffer = fgets($fd, 4096)) !== false) {
    echo $parser->parseLine($buffer);
}

fclose($fd);
